/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.*/



public class evenfibo 
{

	public static void main(String[] args)
	{
		int i;
		int a=0,b=1,sum1=0, sum2=0   ;
		while(sum1<4000000)
		{
		sum1= a+b;
		a=b;
		b=sum1;
		if(sum1%2==0)
		{
			sum2=sum2+sum1;
		}
			
			
		}
		System.out.println("sum="+sum2);

	}

}
